service: fibo

plugins: 
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 4002

provider: 
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  getFiboIndex:
    handler: src/main/delivery/handler.getFiboIndex
    description: 'get fibonacci'
    events: 
      - http:
          path: /{index}
          method: get
          cors: true